name: Minimal reporoduction workflow

on:
  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS cli
        uses: unfor19/install-aws-cli-action@457b7980b125044247e455d87b9a26fc2299b787 # v1
